from distutils.core import setup, Extension

argon2d_hash_module = Extension('argon2d_hash',
                               sources = ['argon2d_module.c',
                                          'argon2d.c',
                                          'sph/extra.c',
                                          'sph/blake.c',
                                          'sph/echo.c', 
                                          'sph/groestl.c',  
                                          'sph/haval.c',    
                                          'sph/keccak.c',  
                                          'sph/shavite.c',  
                                          'sph/SWIFFTX.c',
                                          'sph/bmw.c',  
                                          'sph/fugue.c',
                                          'sph/hamsi.c',    
                                          'sph/luffa.c',   
                                          'sph/simd.c',
                                          'sph/sha2.c',
                                          'sph/sph_sha2.c',
                                          'sph/sph_sha2big.c',
                                          'sph/whirlpool.c',
                                          'sph/cubehash.c',  
                                          'sph/gost_streebog.c',  
                                          'sph/jh.c',  
                                          'sph/sponge.c',
                                          'sph/lyra2.c',   
                                          'sph/shabal.c',  
                                          'sph/skein.c', 
                                          'sph/tiger.c'],
                            include_dirs=['.', './sph'])

setup (name = 'argon2d_hash',
       version = '1.0',
       ext_modules = [argon2d_hash_module])
